apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: httpbin-mtls-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 443
      name: https-mtls
      protocol: HTTPS
    tls:
      mode: MUTUAL
      credentialName: mtls-nonprod-credential # Dedicated secret for mTLS with client CA certificates
    hosts:
    - "mtls.nonprod.domain.net"

