apiVersion: v1
kind: Secret
metadata:
  name: nonprod-credential
  namespace: istio-system
type: kubernetes.io/tls
data:
  # These are base64 encoded placeholders
  # Replace with actual base64 encoded certificate and key
  tls.crt: UkVQTEFDRV9XSVRIX0JBU0U2NF9FTkNPREVEX0NFUlRJRklDQVRF
  tls.key: UkVQTEFDRV9XSVRIX0JBU0U2NF9FTkNPREVEX0tFWQ==

